version: '2'
services:

  testrpc:
    environment:
      - RPC_HOST=testrpc
    build: ./testrpc
    ports:
      - "8545:8545"

  ipfs:
    build: ./ipfs
    ports:
     - "8080:8080"
     - "5001:5001"
     - "4001:4001"
    #  Uncomment this if you want to persist your IPFS data locally
    #  Otherwise it will always be a new instance (no persistence)
    # volumes:
    #   - ~/.ipfs/:/data/ipfs/
    
  functions:
    build:
      context: ./functions
      dockerfile: Dockerfile.serve
    ports:
      - "3001:3001"
    volumes:
     - ./functions/.transmute:/usr/src/app/functions/.transmute
    links:
     - ipfs
     - testrpc

  dapp:
    build:
      context: ./dapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
     - ./dapp/src:/usr/src/app/src
    links:
     - ipfs
     - testrpc
     - functions



