---
- name: helm status ganache
  shell: "helm status ganache | grep STATUS: | awk  '{print $2}' | sed 's/DEPLOYED/yes/g'"
  register: output

- name: Start ganache
  shell: "helm install --name ganache transmute-charts/ganache c"
  when: not output.stdout

- name: ready.w8 ganache
  shell: "$(npm root -g)/transmute-cli/scripts/w8s/ready.w8 ganache default"

- name: minikube_ip
  shell: "minikube ip"
  register: minikube_ip

- name: add ganache.transmute.minikube to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: '{{ minikube_ip.stdout }} ganache.transmute.minikube'
  become: yes

- name: helm status kong
  shell: "helm status gateway | grep STATUS: | awk  '{print $2}' | sed 's/DEPLOYED/yes/g'"
  register: output

- set_fact:
    kong_started: "{{ output.stdout }}"

- name: helm status ipfs
  shell: "helm status decentralized-storage | grep STATUS: | awk  '{print $2}' | sed 's/DEPLOYED/yes/g'"
  register: output
  ipfs_started: "{{ output.stdout }}"
